name: Traffic to Badge

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yi-Xu-0100/traffic-to-badge@main
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          traffic_branch: traffic
          clones_color: blue
          views_color: brightgreen

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: traffic
          publish_dir: .traffic
          keep_files: true

permissions:
  contents: write
